// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBonb0MH65nBKgznC-5BUi9jhgcOkIgvTI',
    appId: '1:846888223741:web:542581b960d5427d260f94',
    messagingSenderId: '846888223741',
    projectId: 'ikraa-a2d87',
    authDomain: 'ikraa-a2d87.firebaseapp.com',
    storageBucket: 'ikraa-a2d87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcKHmfTSVEn4xur3tOSou4gL6Kc1KxIGw',
    appId: '1:846888223741:android:868f815dfe81fbfa260f94',
    messagingSenderId: '846888223741',
    projectId: 'ikraa-a2d87',
    storageBucket: 'ikraa-a2d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCus5HIO-1DylPtX5igR_UjfpgvJI3GmR4',
    appId: '1:846888223741:ios:66daa4f7a618de33260f94',
    messagingSenderId: '846888223741',
    projectId: 'ikraa-a2d87',
    storageBucket: 'ikraa-a2d87.firebasestorage.app',
    iosBundleId: 'com.example.ikraa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCus5HIO-1DylPtX5igR_UjfpgvJI3GmR4',
    appId: '1:846888223741:ios:66daa4f7a618de33260f94',
    messagingSenderId: '846888223741',
    projectId: 'ikraa-a2d87',
    storageBucket: 'ikraa-a2d87.firebasestorage.app',
    iosBundleId: 'com.example.ikraa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBonb0MH65nBKgznC-5BUi9jhgcOkIgvTI',
    appId: '1:846888223741:web:c70a7afafb394482260f94',
    messagingSenderId: '846888223741',
    projectId: 'ikraa-a2d87',
    authDomain: 'ikraa-a2d87.firebaseapp.com',
    storageBucket: 'ikraa-a2d87.firebasestorage.app',
  );
}
